### ISSUE TITLE
role auto_registration_verification errors when auto detecting provider

### ISSUE THREAD

**Issue by gonoph** [RedHatInsights/ansible-collection-subscriptions#9]
redhatinsights.subscriptions.auto_registration_verification : get system product name

Errors when auto detecting provider due to the grep command failing to find the desired text when not running on Google Compute Engine.

This task

```yaml
    - name: get system product name
      shell: sudo dmidecode -s system-product-name | grep "Google Compute Engine"
      register: system_product_name_out
```

should be something like

```yaml
    - name: get system product name
      shell: dmidecode -s system-product-name | grep "Google Compute Engine"
      register: system_product_name_out
      become: true
      failed_when: system_product_name_out.rc and system_product_name_out.stderr
```

though, the above suggestion is still not very "ansible-like", and should probably be performed by grep-like functionality using a jinja2 template inside the playbook.
